<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_Jet
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

/*Ced\Jet\Block\Adminhtml\Order\View\Tab\Shipbyjet $block*/
$resultdata = $block->getModel();// filtered model for current opened order.
if (!empty($resultdata->getData())) {
$jethelper = $block->getHelper('\Jet');
$datahelper = $block->getHelper('\Data');
$error_msg = false;
$show_shipinfo = false;
$number_items = 0;
$row_id= 0;
$orderid = $this->getRequest()->getParam('order_id');
$order_obj = $block->getOrder();
$items=$order_obj->getAllVisibleItems();
foreach ($items as $itemId => $item)
{
	$mag_sku=$item->getSku(); // temp code to bypass jet- mag sku restrictons
}
$returnLocation = $datahelper->getReturnLocation();
$Mage_order_status = $order_obj->getStatus();
foreach ($resultdata as $data)
{
	$jet_status = $data->getStatus();
}
if ($jet_status !='cancelled') {
	$prev_shipinfo = $jethelper->getShipped_Cancelled_Qty($resultdata);
	$order_info = $jethelper->getOrdered_Cancelled_Qty($resultdata);
}
$resultdata = $resultdata->getData();
$block->setOrderResult($resultdata); // setting registry

if (!empty($resultdata) && $resultdata [0] ['status'] != "ready") {
	$row_id = $resultdata [0] ['id'];
	$Order_object = $data = unserialize($resultdata [0] ['order_data']);
	$shipmentdata = unserialize($resultdata [0] ['shipment_data']);
	$merchantorderid = $data->merchant_order_id;

	if ($jet_status == "rejected") {
		$show_shipinfo = false;
		$error_msg = 'This order is <b>Rejected</b> for jet.com';
	} else if ($jet_status == "cancelled") {
		$show_shipinfo = false;
		$error_msg = 'This order is <b>Cancelled</b> for jet.com';
	} else {

		if ($jet_status == 'complete') {
			if (empty($shipmentdata)) {
				$show_shipinfo = false;
			} else {
				$show_shipinfo = true;
			}
		} else {
			$show_shipinfo = false;
		}
	}
} else {
	$error_msg = 'This order either not <b>Acknowledged</b> or it is not a jet.com order';
}

?>
<!-- ===== code start for all different conditions =================== -->
<?php if ($error_msg!=false) { ?>
	<p>
	<h4><?php echo $error_msg; ?></h4>
	<p>
		<?php

		} else if ($show_shipinfo) {
		$info_data = [];
		$info_data ["refer_order_id"] = $data->reference_order_id;
		$info_data ["order_place_date"] =
			date('l, F jS Y \a\t g:ia', strtotime($data->order_placed_date));
		$info_data ["order_transmission_date"] =
			date('l, F jS Y \a\t g:ia', strtotime($data->order_transmission_date));
		$info_data ["request_ship_by"] =
			date('l, F jS Y \a\t g:ia', strtotime($data->order_detail->request_ship_by));
		$info_data ["request_deliver_by"] =
			date('l, F jS Y \a\t g:ia', strtotime($data->order_detail->request_delivery_by));

		?>
		<?php
		$count = 0;
		if ($shipmentdata ["shipments"])
		foreach ($shipmentdata ["shipments"] as $shdata) {

		$info_data ["carrier"] = $shdata ["carrier"];
		$info_data ["method"] = $shdata ["response_shipment_method"];
		$info_data ["shipment_tracking_number"] = $shdata ["shipment_tracking_number"];
		$info_data ["ship_to_date"] = $shdata ["response_shipment_date"];
		$info_data ["expected_delivery_date"] = $shdata ["expected_delivery_date"];
		$info_data ["carrier_pickup_date"] = $shdata ["carrier_pick_up_date"];

		?>

	<div class="admin__page-section-content">
		<div class="admin__page-section-item">
			<div class="admin__page-section-item-title">
				<span class="title">Shipment Information</span>
			</div>
			<div class="admin__page-section-item-content"
				 id="_shipbyjetinfo_table">
				<table class="admin__table-secondary">
					<tbody>
					<tr>
						<th>Reference Order Id on Jet.com</th>
						<td><?php echo $info_data["refer_order_id"]; ?></td>
					</tr>
					<tr>
						<th>Order Placed on Jet.com</th>
						<td><?php echo $info_data["order_place_date"]; ?></td>
					</tr>
					<tr>
						<th>Order transmission on Jet.com</th>
						<td><?php echo $info_data["order_transmission_date"]; ?></td>
					</tr>
					<tr>
						<th>Request Ship By</th>
						<td><?php echo $info_data["request_ship_by"]; ?></td>
					</tr>
					<tr>
						<th>Request Delivery By</th>
						<td><?php echo $info_data ["request_deliver_by"];
							?></td>
					</tr>
					<tr>
						<th>Shipping Carrier</th>
						<td><?php echo $info_data["carrier"]?></td>
					</tr>
					<tr>
						<th>Shipping Method</th>
						<td><?php echo $info_data["method"]?></td>
					</tr>
					<tr>
						<th>Tracking Number</th>
						<td><?php echo $info_data["shipment_tracking_number"]?></td>
					</tr>
					<tr>
						<th>Ship To Date</th>
						<td><?php echo date('l, F jS Y \a\t g:ia', strtotime($info_data ["ship_to_date"]));?></td>
					</tr>
					<tr>
						<th>Expected delivery Date</th>
						<td><?php echo date('l, F jS Y \a\t g:ia', strtotime($info_data ["expected_delivery_date"])); ?></td>
					</tr>
					<tr>
						<th>Carrier Pick Up Date</th>
						<td><?php echo date('l, F jS Y \a\t g:ia', strtotime($info_data ["carrier_pickup_date"])); ?></td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="admin__page-section-title">
		<span class="title">Shipment Items</span>
	</div>
	<div class="admin__table-wrapper">
		<table class="data-table admin__table-primary edit-order-table">
			<thead>
			<tr class="headings">
				<th>Product sku</th>
				<th>Quantity ordered</th>
				<th>Quantity Shipped</th>
				<th>Quantity cancelled</th>
				<th>Return Address</th>
				<th>RMA Number</th>
				<th>Days to Return</th>
			</tr>
			</thead>
			<tbody>
			<?php

			$k = 0;
			foreach ($shdata ["shipment_items"] as $item) {
				if ($item['merchant_sku']) {

					?>
					<tr>
						<td><?php echo $item['merchant_sku']?></td>
						<td><?php echo $Order_object->order_items[$k]->request_order_quantity; ?></td>
						<td><?php echo isset($item['response_shipment_sku_quantity'])?$item['response_shipment_sku_quantity']:0 ;?></td>
						<td><?php echo isset($item['response_shipment_cancel_qty'])?$item['response_shipment_cancel_qty']:0; ?></td>
						<td><?php
							isset($item['return_location']['address1'])
								?
								($address = $item['return_location']['address1'].
									$item['return_location']['address2'].','.$item['return_location']['city'].','.
									$item['return_location']['state'].'-'.$item['return_location']['zip_code'])
								:
								($address = $returnLocation['address1'].
									$returnLocation['address2'].','.$returnLocation['city'].','.
									$returnLocation['state'].'-'.$returnLocation['zip_code']);
							echo $address;
							?>
						</td>
						<td><?php echo isset($item['RMA_number'])?  $item['RMA_number'] : 'N/A';?></td>
						<td><?php echo isset($item['days_to_return'])?  $item['days_to_return'] :  'N/A';?></td>
					</tr>
				<?php  } ?>
				<?php $k++; }  ?>
			</tbody>
		</table>
	</div>

	<?php $count++; } ?>

	<h3>Order Shipped Successfully</h3>
<?php } else { ?>
	<p>
		<input type="hidden" id="orderid" value="<?php echo $data->merchant_order_id ?>" readonly>
		<input type="hidden" id="incrementid" value="<?php echo $block->getOrder()->getIncrementId() ?>"> <input
			type="hidden" id="form_key" value="<?php echo $block->getFormKey();?>">
		<input type="hidden" id="magento_orderid"
			   value="<?php echo $orderid ?>">
	</p>

	<!-- coomon -->
	<div class="admin__page-section-content">
		<div class="admin__page-section-item">
			<div class="admin__page-section-item-title">
				<span class="title">Shipment Information</span>
			</div>
			<div class="admin__page-section-item-content">
				<table class="admin__table-secondary">
					<tbody>
					<tr>
						<th>Reference Order Id on Jet.com</th>
						<td><?php echo $data->reference_order_id; ?></td>
					</tr>
					<tr>
						<th>Order Placed on Jet.com</th>
						<td><?php  echo date('l, F jS Y \a\t g:ia',strtotime($data->order_placed_date)); ?></td>
					</tr>
					<tr>
						<th>Order transmission on Jet.com</th>
						<td><?php echo date('l, F jS Y \a\t g:ia',strtotime($data->order_transmission_date)); ?></td>
					</tr>
					<tr>
						<th>Request Ship By</th>
						<td><?php echo date('l, F jS Y \a\t g:ia',strtotime($data->order_detail->request_ship_by)); ?></td>
					</tr>
					<tr>
						<th>Request Delivery By</th>
						<td><?php echo date('l, F jS Y \a\t g:ia',strtotime($data->order_detail->request_delivery_by)); ?></td>
					</tr>
					<tr>
						<th>Shipping Carrier</th>
						<?php $flag=true;
						if ($data->order_detail->request_shipping_carrier !="" && $flag) { ?>
							<td><input class="admin__control-text" type="text" id="carrier" value="<?php echo  $data->order_detail->request_shipping_carrier?>">
							</td>
							<?php $flag = false;
						} else {  ?> 
                            <td>
                                <?php echo $this->getJetShipCarrier(); ?>
							</td>
						<?php }?>
					</tr>
					<tr>
						<th>Shipping Method</th>
						<?php $flag=true;
						if ($data->order_detail->request_shipping_method !="" && $flag) { ?>
							<td><input class="admin__control-text" type="text" id="method" value="<?php echo  $data->order_detail->request_shipping_method ?>">
							</td>
							<?php $flag = false;
						} else {  ?> 
                            <td>
                                <?php echo $this->getJetShipMethod(); ?>
							</td>
						<?php }?>
					</tr>
					<tr>
						<th>Request Service Level</th>
						<td><input class="admin__control-text" type="text" id="request_service_level"
								   value="<?php echo  $data->order_detail->request_service_level?>"></td>
					</tr>
					<tr>
						<th>Tracking Number</th>
						<td><input class="admin__control-text" type="text" id="tracking" value=""></td>
					</tr>
					<tr>
						<th>Ship To Date</th>
						<td><input class="admin__control-text input-text required-entry"  type="text" id="ship_date" name="ship_date" /></td>
					</tr>
					<tr>
						<th>Carrier Pick Up Date<br><br><br>Expected delivery Date(respectively)</th>
						<td><div class="admin__field _required" data-role="filter-form" id="date_range">
								<input class="admin__control-text"  type="text" id="car_pickdate" name="car_pickdate" /><br/><br/>
								<input class="admin__control-text" type="text" id="ex_deliverydate" name="ex_deliverydate" />
							</div>
						</td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="admin__page-section-title">
		<span class="title">Shipment Items</span>
	</div>
	<div class="admin__table-wrapper">
		<table class="data-table admin__table-primary edit-order-table" id="_prod_table">
			<thead>
			<tr class="headings">
				<th>Product sku</th>
				<th>Quantity ordered</th>
				<th>Quantity to Ship</th>
				<th>Quantity to Cancel</th>
				<th>Qty Available for ship</th>
				<th>Return Address</th>
				<th>RMA Number</th>
				<th>Days to Return</th>
			</tr>
			</thead>
			<tbody id="item">
			<?php

			foreach ($data->order_items as $k=>$valdata) { $number_items++;
				$cancel_qty = 0;
				if (isset($prev_shipinfo [$valdata->merchant_sku] ['response_shipment_cancel_qty'] )) {
					$real_cancel_qty = $prev_shipinfo [$valdata->merchant_sku] ['response_shipment_cancel_qty'];
				} else {
					$real_cancel_qty = 0;
				}
				//by pass order sku multiple shipment restriction

				if (isset($prev_shipinfo[$valdata->merchant_sku]) && $prev_shipinfo) {
					$avail_qty =($valdata->request_order_quantity -($prev_shipinfo [$valdata->merchant_sku]
							['response_shipment_sku_quantity'] + $real_cancel_qty));
				} else {
					$avail_qty = $valdata->request_order_quantity;
				}

				$ship_qty =(int)($valdata->request_order_quantity);
				if ($avail_qty > 0) {
					?>
					<tr>
					<td><input type="hidden" id="sku_<?php echo $k;?>" value="<?php echo $valdata->merchant_sku?>">
						<strong><?php echo $valdata->merchant_sku; ?></strong>
					</td>
					<td><input type="hidden" id="qty_<?php echo $k;?>" value="<?php echo $valdata->request_order_quantity ?>">
						<strong><?php echo $valdata->request_order_quantity ?></strong>
					</td>
					<?php if ($avail_qty > 0): ?>
						<td><input class="admin__control-text" type="text" maxlength="70" id="ship_<?php echo $k;?>"
								   value="<?php echo $avail_qty;?>" onkeypress="return isNumberKey(event);">
						</td>
						<td><input class="admin__control-text" type="text" id="can_<?php echo $k;?>"
								   value="<?php echo $cancel_qty;?>">
						</td>
					<?php else : ?>
						<td><input type="hidden" id="ship_<?php echo $k;?>" value="<?php echo $avail_qty ?>">
							<strong <?php if ($avail_qty <= 0) {echo ' style="color: #EE0000" ';} ?>>
								<?php echo $avail_qty ?>
							</strong>
						</td>
						<td><input type="hidden" id="can_<?php echo $k;?>"value="<?php echo $cancel_qty;?>">
							<strong <?php if ($avail_qty <= 0) {echo ' style="color: #EE0000" ';} ?>>
								<?php echo $cancel_qty ?>
							</strong>
						</td>
					<?php endif;?>
					<td><input type="hidden" id="avail_<?php echo $k;?>" value="<?php echo $avail_qty ?>">
						<strong <?php if ($avail_qty > 0) {echo ' style="color: #008800" ';} else {echo ' style="color: #EE0000" ';} ?>>
							<?php echo $avail_qty ?>
						</strong>
					</td>
					<td><select class="admin__control-select" name="address" id="address_<?php echo $k; ?>" onchange="">
							<option value="" disabled="disabled" >Please select a option</option>
							<option value="1" selected="selected">Yes</option>
							<option value="0">No</option>
						</select>
					</td>
					<!-- Rma input -->
					<td><input class="admin__control-text" type="text" id="rma_<?php echo $k;?>" value=""></td>
					<td><input class="admin__control-text" type="text" id="days_return_<?php echo $k;?>" value="" placeholder="0"
							   onkeypress="return isNumberKey(event);">
					</td>
					<!--<td></td>-->
					</tr><?php } } ?>
			</tbody>
		</table>
	</div>
	<br/><button class="primary" id="button1" onclick="CallShipment();">Submit
		Shipment</button><br/>

	<?php
	if ($jet_status == 'inprogress') {
		$info_data = [];
		$info_data["refer_order_id"] = $data->reference_order_id;
		$info_data["order_place_date"] = date('l, F jS Y \a\t g:ia', strtotime($data->order_placed_date));
		$info_data["order_transmission_date"] = date('l, F jS Y \a\t g:ia', strtotime($data->order_transmission_date));
		$info_data["request_ship_by"] = date('l, F jS Y \a\t g:ia', strtotime($data->order_detail->request_ship_by));
		$info_data["request_deliver_by"] = date('l, F jS Y \a\t g:ia', strtotime($data->order_detail->request_delivery_by));
		?>
		<div class="admin__page-section-title">
			<span class="title">Shipment History</span>
		</div>
		<?php
		$count = 0 ;
		foreach ($shipmentdata["shipments"] as $shdata) {

			$info_data["carrier"] = $shdata["carrier"];
			$info_data ["method"] = $shdata ["response_shipment_method"];
			$info_data["shipment_tracking_number"] = $shdata["shipment_tracking_number"];
			$info_data["ship_to_date"] = $shdata["response_shipment_date"];
			$info_data["expected_delivery_date"] = $shdata["expected_delivery_date"];
			$info_data["carrier_pickup_date"] = $shdata["carrier_pick_up_date"];

			?>

			<div class="admin__page-section-content">
				<div class="admin__page-section-item">
					<div class="admin__page-section-item-title">
						<span class="title">Shipment Information</span>
					</div>
					<div class="admin__page-section-item-content"
						 id="_shipbyjetinfo_table">
						<table class="admin__table-secondary">
							<tbody>
							<tr>
								<th>Reference Order Id on Jet.com</th>
								<td><?php echo $info_data["refer_order_id"]; ?></td>
							</tr>
							<tr>
								<th>Order Placed on Jet.com</th>
								<td><?php echo $info_data["order_place_date"]; ?></td>
							</tr>
							<tr>
								<th>Order transmission on Jet.com</th>
								<td><?php echo $info_data["order_transmission_date"]; ?></td>
							</tr>
							<tr>
								<th>Request Ship By</th>
								<td><?php echo $info_data["request_ship_by"]; ?></td>
							</tr>
							<tr>
								<th>Request Delivery By</th>
								<td><?php echo $info_data ["request_deliver_by"];
									?></td>
							</tr>
							<tr>
								<th>Shipping Carrier</th>
								<td><?php echo $info_data["carrier"]?></td>
							</tr>
							<tr>
								<th>Shipping Method</th>
								<td><?php echo $info_data["method"]?></td>
							</tr>
							<tr>
								<th>Tracking Number</th>
								<td><?php echo $info_data["shipment_tracking_number"]?></td>
							</tr>
							<tr>
								<th>Ship To Date</th>
								<td><?php echo date('l, F jS Y \a\t g:ia', strtotime($info_data ["ship_to_date"]));?></td>
							</tr>
							<tr>
								<th>Expected delivery Date</th>
								<td><?php echo date('l, F jS Y \a\t g:ia', strtotime($info_data ["expected_delivery_date"])); ?></td>
							</tr>
							<tr>
								<th>Carrier Pick Up Date</th>
								<td><?php echo date('l, F jS Y \a\t g:ia', strtotime($info_data ["carrier_pickup_date"])); ?></td>
							</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="admin__page-section-title">
				<span class="title">Shipment Items</span>
			</div>
			<div class="admin__table-wrapper">
				<table class="data-table admin__table-primary edit-order-table">
					<thead>
					<tr class="headings">
						<th>Product sku</th>
						<th>Quantity ordered</th>
						<th>Quantity Shipped</th>
						<th>Quantity cancelled</th>
						<th>Return Address</th>
						<th>RMA Number</th>
						<th>Days to Return</th>
					</tr>
					</thead>
					<tbody>
					<?php

					$k = 0;
					foreach ($shdata ["shipment_items"] as $item) {
						if ($item['merchant_sku']) {

							?>
							<tr>
								<td><?php echo $item['merchant_sku']?></td>
								<td><?php echo $Order_object->order_items[$k]->request_order_quantity; ?></td>
								<td><?php echo isset($item['response_shipment_sku_quantity'])?$item['response_shipment_sku_quantity']:0 ;?></td>
								<td><?php echo isset($item['response_shipment_cancel_qty'])?$item['response_shipment_cancel_qty']:0; ?></td>
								<td><?php
									isset($item['return_location']['address1'])
										?
										($address = $item['return_location']['address1'].
											$item['return_location']['address2'].','.$item['return_location']['city'].','.
											$item['return_location']['state'].'-'.$item['return_location']['zip_code'])
										:
										($address = $returnLocation['address1'].
											$returnLocation['address2'].','.$returnLocation['city'].','.
											$returnLocation['state'].'-'.$returnLocation['zip_code']);
									echo $address;
									?>
								</td>
								<td><?php echo isset($item['RMA_number'])?  $item['RMA_number'] : 'N/A';?></td>
								<td><?php echo isset($item['days_to_return'])?  $item['days_to_return'] :  'N/A';?></td>
							</tr>
						<?php  } ?>
						<?php $k++; }  ?>
					</tbody>
				</table>
			</div>

			<?php $count++; } ?>

		<h3>Order Shipped Successfully</h3>
	<?php } ?>
	<p>
		<strong>NOTE:</strong>
	<ul>
		<li><b>*RMA_number:(optional)</b>&nbsp; The RMA # in your system
			associated with this order item if returned</li>
		<br />
		<li><b>*Days to Return:</b>&nbsp; The number of days the customer has
			to return the shipment item</li>
		<br />
		<li><b>*Request Ship By Date</b>&nbsp; Expected date that the shipment
			will be tendered to the given carrier.</li>
		<br />
		<li><b>*Request Ship By Logic</b> This will be calculated based on when
			the merchant order is sent the Merchant and their given settings for
			fulfilment time, and order cutoff data set at either the account level
			or shipping method level.</li>
		<br />
		<li><b>*Request Delivery By Date</b>&nbsp; Date the customer has been
			promised delivery.</li>
		<br />
		<li><b>Request Delivery By Logic</b> The ShippingMethod selected should
			provide delivery by this date as long as you meet shipping
			requirements you communicated during shipping set up. If you use Jet
			provided labels and ship ontime you should meet this date. If you use
			your own shipping labels, you can choose to use a carrier other than
			the one suggested by ShippingMethod as long as the DeliveryByDate is
			met or exceeded.</li>
		<br />
		<li><b>*Order Transmission Date</b> The date/time the merchant order
			was sent to the merchant.</li>
		<br />
	</ul>
	</p>
	<script>
		require([
			"jquery",
			"mage/calendar"
		], function($) {
			$("#ship_date").calendar({
				showsTime: false,
				hideIfNoPrevNext: true,
				buttonText:"<?php echo __('Select Date') ?>",
				dateFormat: "yy-mm-dd",
				minDate: new Date()
			});
			$("#car_pickdate").calendar({
				showsTime: false,
				hideIfNoPrevNext: true,
				buttonText:"<?php echo __('Select Date') ?>",
				dateFormat: "yy-mm-dd",
				minDate: new Date()
			});
			$("#ex_deliverydate").calendar({
				showsTime: false,
				hideIfNoPrevNext: true,
				buttonText:"<?php echo __('Select Date') ?>",
				dateFormat: "yy-mm-dd",
				minDate: new Date()
			});
			$("#date_range").dateRange({
				buttonText:"<?php echo __('Select Date') ?>",
				from:{
					id:"car_pickdate"
				},
				to:{
					id: "ex_deliverydate"
				}
			});
		});
	</script>
	<script>
		function isNumberKey(evt) {
			var charCode =(evt.which) ? evt.which : event.keyCode;
			if (charCode != 46 && charCode > 31
				&&(charCode < 48 || charCode > 57))
				return false;

			return true;
		}

		function CallShipment() {
			var key=document.getElementById('form_key').value;
			var id=document.getElementById('incrementid').value;
			var ids=document.getElementById('magento_orderid').value;
			var orderid=document.getElementById('orderid').value;
			var carrier=document.getElementById('carrier').value;
			var method=document.getElementById('method').value;
			var rsl=document.getElementById('request_service_level').value;
			var tracking=document.getElementById('tracking').value;
			var ship_todate=document.getElementById('ship_date').value;
			var exp_deliver=document.getElementById('ex_deliverydate').value;
			var carre_pickdate=document.getElementById('car_pickdate').value;
			var shipmonth = parseInt(ship_todate.substring(5,8));
			var shipdate = parseInt(ship_todate.substring(8,11));
			var pickmonth = parseInt(carre_pickdate.substring(5,8));
			var pickdate = parseInt(carre_pickdate.substring(8,11));

			

			var jet_order_detail_row =  <?php echo $row_id; ?>

			var outterArray = [];
			var lengthval = <?php echo $number_items; ?>;


			for(var i=0; i<lengthval;  i++) {
				if (document.getElementById('sku_'+i)){
					product_sku = document.getElementById('sku_'+i).value;
					requested_quantity = document.getElementById('qty_'+i).value;
					cancel_quantity = document.getElementById('can_'+i).value;
					ship_quantity = document.getElementById('ship_'+i).value;
					avail_check_quantity = document.getElementById('avail_'+i).value;
					days_to_return =  document.getElementById('days_return_'+i).value;
					test = requested_quantity - cancel_quantity;
					checkQty = ship_quantity - cancel_quantity;

					if (isNaN(parseInt(test)) || isNaN(parseInt(checkQty)) || isNaN(parseInt(ship_quantity)) || isNaN(parseInt(cancel_quantity))) {
						alert("Please enter ship and cancel quantity numeric");
						return;
					}
					if (ship_quantity > test) {
						alert("Item Sku: "+product_sku+" Total shipping/cancellation quantity can not exceed from ordered quantity ");
						return;
					}
					
					if (parseInt(ship_quantity) <= 0 &&  parseInt(cancel_quantity) <= 0) {
						alert("please enter Quantity to Ship or Quantity to Cancel greater than zero");
						return;
					}

					if((parseInt(ship_quantity) + parseInt(cancel_quantity)) > parseInt(avail_check_quantity)) {
						alert("Item Sku: "+product_sku+" Please provide either shipping quantity or cancel quantity for item");
						return;
					}

					if (days_to_return < 7) {
						days_to_return = 7;
					}
					if (ship_quantity < 1) {
						var check = false;
					} else {
						var check = true;
					}
					var product_data = [product_sku,
						requested_quantity,
						cancel_quantity,
						document.getElementById('address_'+i).value,
						document.getElementById('rma_'+i).value,
						days_to_return,
						ship_quantity,
						document.getElementById('avail_'+i).value]; // new quantity to ship added
					//shipment id removed
					outterArray.push(product_data);
				}
			}

			if (check) {
				if (carrier=="") {
					alert("Please enter Shipping carrier");
					return;
				}
				if (method=="") {
					alert("Please enter Shipping Method");
					return;
				}
				if (rsl=="") {
					alert("Please enter Request Service Level");
					return;
				}
				if (tracking=="") {
					alert("Please Enter Tracking Number");
					return;
				}
				if (ship_todate=="") {
					alert("Please enter Ship to date");
					return;
				}
				if (exp_deliver=="") {
					alert("Please enter expected delivery date");
					return;
				}
				if (carre_pickdate=="") {
					alert("Please enter Carrier Pick Up Date");
					return;
				}
				if (shipdate > pickdate) {
					if (shipmonth >= pickmonth)
						alert("pick up date should be greater than shippment date");
					return;
				}
			}
			
			if (carrier == 'USPS First Class Mail' || carrier == 'UPS Ground') {carrier = 'UPS';}
			new Ajax.Request("<?php echo $this->getUrl('jet/order/ship') ?>", {
				method: 'Post',
				parameters: {"orderid":orderid,"items":JSON.stringify(outterArray),"request_service_level":rsl,"carrier":carrier,"method":method,"key1":id,"order":ids,"tracking":tracking,"ship_todate":ship_todate,"exp_deliver":exp_deliver,"carre_pickdate":carre_pickdate,"order_table_row":jet_order_detail_row},

				onComplete: function(transport) {
					if (transport.responseText == "Success") {
						try {
							window.location.href=window.location.href;
						}
						catch(err) {
							alert(transport.responseText);
						}
					} else {
						alert(transport.responseText);
					}
				}
			});

		}

	</script>
<?php } ?>
<style>
	#item >tr >td > input , select{
		width:100% !important;
	}
</style>
<?php } ?>
