<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct();  ?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$categories = $product->getCategoryIds(); /*will return category ids array*/

$catname = array();
foreach($categories as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    if($cat->getParentId() != 8){
		$catname[] = $cat->getName();  
	}
}
$brandname = $_product->getData('brand');
$sub_cat1 = $_product->getData('sub_cat');
$prd_col = $_product->getData('color_bar');
$country_name = '';
foreach($categories as $category){
	$cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
	if($cat->getParentId() == 8){
		$country_name = $cat->getName();
	}

}
?>
<div class="prdct-attribute"> 
<div class="cat_outer">                  
	<?php $count = count($catname); ?>
		<?php if($count !="" || $catname == ""){ ?>
			<span class="product_page_title">Category: </span>
				<span class="product_page_title_value">   
				<?php $ci=1;?>
				<?php foreach($catname as $cn){ ?>
					<?php if($ci==$count){?>
					<?php echo $cn; ?>
					<?php }else{?>
						<?php echo $cn.","; ?>
					<?php } ?>
				</span>                    
				<?php $ci++; ?>
				<?php } ?>
		<?php } ?>
	</div>

	<?php if($sub_cat1 != "") {?>
		<div class="sub_cat_outer"><span class="product_page_title">Sub Category: </span>
		<span class="product_page_title_value"><?php echo $sub_cat1; ?></span></div>
	<?php } ?>
		<div class="country_outer"><span class="product_page_title">Country:&nbsp; </span><span class="product_page_title_value"><?php echo $country_name; ?></span></div>
	<?php if($brandname !=""){?>
		<div class="brand_outer"><span class="product_page_title">Brand:&nbsp; </span><span class="product_page_title_value"><?php echo $brandname; ?></span></div>
	<?php } ?>
		<div class="sku_outer"><span class="product_page_title">Sku:&nbsp; </span><span class="product_page_title_value"><?php echo $_product->getSku(); ?></span></div>
</div> 


<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty:') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty spintest"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="more_info_outer" style="display:none">

<a href="javascript:void(0)" data="<?php echo $_product->getProductUrl();?>" class="more_info_link">More Information</a>
</div>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<script>
require([
         'jquery'        
         ],
         function($, click) {
			$('.more_info_link').on( "click", function() {
				var product_url = $(this).attr("data");				
				window.parent.location.href = product_url;
				/*
				   window.close();
			    window.open(
			    		product_url,
			    		'_blank'
			    		);
			 
			   /* window.location.href = product_url;
				/*$('.mfp-close').trigger("click");
				$(".mfp-iframe").css({"display": 'none'});			
					alert('dsf');
					$.magnificPopup.close();
					$('.mfp-close').trigger('click');
				 
					$("#id").css("display", "none");
					jQuery('.mfp-close').trigger('click');
					var product_url = $(this).attr("data");
				    alert(product_url);
					window.location.href = product_url;
				*/
				
			});              
         }
         
    );
</script>