<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info1', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
			<?php /* foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php  echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php echo $alias; ?>"
                       id="tab-label-<?php echo $alias;?>-title">
                        <?php echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php echo $alias; ?>" data-role="content">
                    <?php echo $html; ?>
                </div>
            <?php endforeach; */?>
            
            <?php 
				/* Custom code by TPSS */
				$product = $block->getProduct(); 
				$custom_tab_3 = 'Description';			
			?>
			         
			<div class="data item title" aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_3;?>-title"
				 data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_3;?>">
				<a class="data switch"
				   tabindex="-1"
				   data-toggle="switch"
				   href="#<?php /* @escapeNotVerified */ echo $custom_tab_3; ?>"
				   id="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_3;?>-title">
					<?php /* @escapeNotVerified */ echo $custom_tab_3; ?>
				</a>
			</div>
			<div class="data item content" id="<?php /* @escapeNotVerified */ echo $custom_tab_3; ?>" data-role="content">
				<?php echo $product->getData('description'); ?>
			</div>
            
			<?php $custom_tab_1 = 'Nutritional'; ?>
			         
			<div class="data item title" aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_1;?>-title"
				 data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_1;?>">
				<a class="data switch"
				   tabindex="-1"
				   data-toggle="switch"
				   href="#<?php /* @escapeNotVerified */ echo $custom_tab_1; ?>"
				   id="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_1;?>-title">
					<?php /* @escapeNotVerified */ echo $custom_tab_1; ?>
				</a>
			</div>
			<div class="data item content" id="<?php /* @escapeNotVerified */ echo $custom_tab_1; ?>" data-role="content">
				<?php echo $product->getData('nutritional'); ?>
			</div>
			
			<?php $custom_tab_2 = 'Alegen'; ?>
			         
			<div class="data item title" aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_2;?>-title"
				 data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_2;?>">
				<a class="data switch"
				   tabindex="-1"
				   data-toggle="switch"
				   href="#<?php /* @escapeNotVerified */ echo $custom_tab_2; ?>"
				   id="tab-label-<?php /* @escapeNotVerified */ echo $custom_tab_2;?>-title">
					<?php /* @escapeNotVerified */ echo $custom_tab_2; ?>
				</a>
			</div>
			<div class="data item content" id="<?php /* @escapeNotVerified */ echo $custom_tab_2; ?>" data-role="content">
				<?php echo $product->getData('xxxx'); ?>
			</div>
			
            <?php /* Custom code by TPSS END*/ ?>

        </div>
    </div>
<?php endif; ?>
