<?php
$root_category = Mage::getModel('catalog/category')->load(2);
$subcategories = $root_category->getChildren();
$i = 0;
foreach(explode(',',$subcategories) as $subcategory) {  
    if($subcategory != 8){
    $category = Mage::getModel('catalog/category')->load($subcategory);
    $caturl = $category->getUrl();
    $catname = $category->getName();    
    $pid = array();    
    foreach ($category->getProductCollection() as $product) {
       $pid[] = $product->getId();
    }    
    $randomid = $pid[array_rand($pid)];    
    $product= Mage::getModel('catalog/product')->load($randomid);
    $margin="";
       
       switch ($i){
           case 0: $width='56%';  break;
           case 1: $width='42%';  break;
           case 2: $width='32%';  break;
           case 3: $width='35%'; $margin='margin:2px 4px'; break;
           case 4: $width='30%';  break;
           case 5: $width='30%'; $height='500px';  break;
           case 6: $width='30%'; $height='245px'; break;
           case 7: $width='37%'; $height='500px'; break;
           case 8: $width='41%'; $height='220px'; $margin='margin-right:6px;';  break;
           case 9: $width='56%'; $height='220px'; break;
           case 10: $width='49%'; $height='220px'; $margin='margin-right:6px;'; break;
           case 11: $width='48%'; $height='220px'; $margin='margin-right:2px;';break;
           case 12: $width='32%'; $margin='margin-right:4px;'; break;
           case 13: $width='24%';  break;
           case 14: $width='32%';  break;
           case 15: $width='406px';  break;
           default : $width='30%'; break;
     }
     
     /* first set */ 
     $imageurl = Mage::helper('catalog/image')->init($product, 'image')->keepFrame(false)->resize();
     
     if( $i < 5){         
         if($i == 0){
            echo "<div style='float:left; width:100%;'>"; 
            echo "<div style='width:75%;float:left;'>";
            echo "<div style='float:left; width:100%;'>";
         }
         if($i==2){echo "<div style='float:left; width:100%;'>";}
            echo "<div class='home-images' style='width:".$width."; height:200px;'><a class='homeimg-link' href='".$caturl."' ><img style='width:100%; height:100%;' src='".$imageurl."' alt='' /></a>
            <div class='home-imgtitle'><span>".$catname."</span><span class='home-arwimg'></span></div>    
            </div>";
       
        if($i==1){echo "</div>";}    
        if($i == 4){
              echo "</div>";
              echo "</div>";
              echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-ad-image')->toHtml();
              echo "</div>";
        }
    }
    
    /* first set ends here */ 
    
    
    
    
    /* second set*/
    
    if($i>4 && $i < 8){        
      
        if($i==5){         
           echo "<div style='float:left;width:100%;'>";
        }
        if($i == 6){
             echo '<div style="float:left; width:31%; height:500px; margin:2px 4px;" >'.$this->getLayout()->createBlock('cms/block')->setBlockId('friends-club')->toHtml().
             "<div class='' style=' height: 250px; width: 99%;'><a class='homeimg-link' style=' float: left; height: 100%; width: 100%;' href='".$caturl."' ><img style='width:100%; height:100%;' src='".$imageurl."' alt='' /></a>
            <div class='home-imgtitle'><span>".$catname."</span><span class='home-arwimg'></span></div>    
            </div>
            </div>";
        }
        if($i != 6){
            echo "<div class='home-images' style='width:".$width."; height:".$height.";'><a class='homeimg-link' href='".$caturl."' ><img style='width:100%; height:100%;' src='".$imageurl."' alt='' /></a>
            <div class='home-imgtitle'><span>".$catname."</span><span class='home-arwimg'></span></div>    
            </div>";
        }
            
        if($i == 7){
          echo "</div>";
        }
    }
    /* second set ends here */
    
    
    
    /* third set */
    if($i > 7 && $i < 13 ){       
      
       
       if($i < 12){
        if( $i == 8){  
            echo "<div style='float:left; width:100%;'>";
            echo "<div style='float: left; height: 450px; width:66%; margin-right:4px;'>";
            echo "<div style='float: left; width:100%;'>";
        }
        if($i == 10){echo "<div style='float: left; width:100%;'>";}
        echo "<div class='home-images' style='width:".$width."; height:".$height.";".$margin." float:left;'><a class='homeimg-link' href='".$caturl."' ><img style='width:100%; height:100%;' src='".$imageurl."' alt='' /></a>
        <div class='home-imgtitle'><span>".$catname."</span><span class='home-arwimg'></span></div>    
        </div>";
        if($i==9){echo "</div>";}
        if( $i == 11){
            echo "</div></div>";
        }
       }     
       
       if( $i == 12){           
         echo "<div style=' float: left; height: 445px; margin-top: 2px; width: 33%;'>
                <a style='float:left; width:100%; height:100%;' href='".$caturl."' ><img style='width:100%; height:100%;' src='".$imageurl."' alt='' /></a>
                <div class='home-imgtitle'><span>".$catname."</span><span class='home-arwimg'></span></div>    
        </div>";
        echo "</div>"; 
       }  
       
    }
    /* third set ends here */
   
    
    /* Fourth set */
    if( $i > 12 && $i < 16 ){       
        if($i==13){            
            echo "<div style='float:left; width:100%; height:270px; margin-top:2px;margin-bottom:6px;'>";
        }        
        echo "<div style=' float:left; height:100%; margin:2px 4px;".$margin."width:".$width."'>
                <a style='float:left; width:100%; height:100%;' href='".$caturl."' ><img style='width:100%; height:100%;' src='".$imageurl."' alt='' /></a>
                <div class='home-imgtitle'><span>".$catname."</span><span class='home-arwimg'></span></div>    
        </div>";
        if($i==15){
            echo "</div>";
        }
    }
    /* Fourth set ends here */
    
    
    /*default*/
//    if( $i>15){
//      echo "<div style='border:1px solid #717171; float:left; height:225px; margin:2px 4px;".$margin."width:".$width."'>
//                <a style='float:left; width:100%; height:100%;' href='".$caturl."' ><img style='width:100%; height:100%;' src='".$imageurl."' alt='' /></a>
//                <div class='home-imgtitle'><span>".$catname."</span><span class='home-arwimg'></span></div>    
//        </div>";      
//    }
    /* default */
    
   
    
    
    $i++;
    }
}

?>


