<?php
$cat = Mage::getModel('catalog/category')->load(8);
$subcats = $cat->getChildren();
$i=0;
foreach(explode(',',$subcats) as $subCatid)
{   
      $_category = Mage::getModel('catalog/category')->load($subCatid);      
      $caturl     = $_category->getURL();
      $catname     = $_category->getName();
      $margin = "";
      if($_category->getImageUrl())
        {
          
          switch ($i){
           case 0: $width='30%'; $height='550px'; break;
           case 1: $width='25%'; $height='280px'; break;
           case 2: $width='43%'; $height='280px'; break;
           case 3: $width='32%'; $height='266px'; break;
           case 4: $width='36%'; $height='266px'; break;
           case 5: $width='36%'; $height='450px'; break;
           case 6: $width='100%'; $height='49%'; $margin='margin:0px 0px 4px 0px;'; break;
           case 7: $width='100%'; $height='50%'; $margin='margin:0;'; break;
           case 8: $width='32%'; $height='450px'; break;
           case 9: $width='26%'; $height='450px'; break;
           case 10: $width='30%'; $height='100%'; $margin='margin:0 4px 0 2px;'; break;
           case 11: $width='69%'; $height='100%'; $margin='margin:0;'; break;
           case 12: $width='41%'; $height='100%'; $margin='margin:0 2px 0 0;'; break;
           case 13: $width='58%'; $height='100%'; $margin='margin: 0 2px;'; break;
           case 14: $width='45%'; $height='450px'; break;
           case 15: $width='54%'; $height='223px'; break;
           case 16: $width='54%'; $height='223px'; break;
           case 17: $width='26%'; $height='450px'; break;
           case 18: $width='30%'; $height='100%'; $margin='margin:0 4px 0 2px;'; break;
           case 19: $width='69%'; $height='100%'; $margin='margin:0;'; break;
           case 20: $width='41%'; $height='100%'; $margin='margin:0 2px 0 0;'; break;
           case 21: $width='58%'; $height='100%'; $margin='margin: 0 2px;'; break;
           case 22: $width='45%'; $height='450px'; break;
           case 23: $width='54%'; $height='223px'; break;
           case 24: $width='54%'; $height='223px'; break;
           default : $width='30%';
               break;
           }
          $catimg  = $_category->getImageUrl();       
          /* first block */
          if($i < 5){
            if($i == 0){ echo "<div style='float:left; width:100%;'>"; }  
            echo '<div class="home-images" style="width:'.$width.'; height:'.$height.'; border:none;"><a class="homeimg-link" href="'.$caturl.'" title="View the products for this category"><img style="width:100%; height:100%;" src="'.$catimg.'" alt="" /></a>
            <div class="home-imgtitle"><span>'.$catname.'</span><span class="home-arwimg"></span></div></div>';      
            if($i==4){ echo "</div>"; }
          }
          /* first ends */
          
          /* second block */
          if($i > 4 && $i < 9){
            if($i == 5){ echo "<div style='float:left; width:100%;'>"; }
            if($i == 6){ echo "<div style='float:left; width:30%; height:450px;margin:2px;'>"; }
                echo '<div class="home-images" style="width:'.$width.'; height:'.$height.'; border:none;'.$margin.'"><a class="homeimg-link" href="'.$caturl.'" title="View the products for this category"><img style="width:100%; height:100%;" src="'.$catimg.'" alt="" /></a>
                <div class="home-imgtitle"><span>'.$catname.'</span><span class="home-arwimg"></span></div></div>';      
            if($i == 7){ echo "</div>"; }
            if($i==8){ echo "</div>"; }
          }
          /* second ends */
          
          
          /* Third block */
          if($i > 8 && $i < 14){
            if($i == 9){ echo "<div style='float:left; width:100%;'>"; }
            if($i==10 ){ echo "<div style='float: left;height: 223px; margin-top: 2px;width: 73%;'>"; }
            if($i==12 ){ echo "<div style=' float: left; height: 223px; margin-left: 2px; margin-top: 4px; width: 73%;'>"; }
            echo '<div class="home-images" style="width:'.$width.'; height:'.$height.'; border:none;'.$margin.'"><a class="homeimg-link" href="'.$caturl.'" title="View the products for this category"><img style="width:100%; height:100%;" src="'.$catimg.'" alt="" /></a>
                <div class="home-imgtitle"><span>'.$catname.'</span><span class="home-arwimg"></span></div></div>';      
            if($i==11 || $i==13){echo "</div>";}                   
            if($i==13){ echo "</div>"; }                   
          }
          /* Third ends */
          
          
          /*Forth block*/
          if($i > 13 && $i < 17){
              if($i == 14){ echo "<div style='float:left; width:100%;'>"; }
              
              echo '<div class="home-images" style="width:'.$width.'; height:'.$height.'; border:none;'.$margin.'"><a class="homeimg-link" href="'.$caturl.'" title="View the products for this category"><img style="width:100%; height:100%;" src="'.$catimg.'" alt="" /></a>
                <div class="home-imgtitle"><span>'.$catname.'</span><span class="home-arwimg"></span></div></div>';     
              
              if($i == 16){ echo "</div>"; }
          }
          /*Forth ends*/
          
          /* Fifth block */
          if($i > 16 && $i < 22){
            if($i == 17){ echo "<div style='float:left; width:100%;'>"; }
            if($i==18 ){ echo "<div style='float: left;height: 223px; margin-top: 2px;width: 73%;'>"; }
            if($i==20 ){ echo "<div style=' float: left; height: 223px; margin-left: 2px; margin-top: 4px; width: 73%;'>"; }
            echo '<div class="home-images" style="width:'.$width.'; height:'.$height.'; border:none;'.$margin.'"><a class="homeimg-link" href="'.$caturl.'" title="View the products for this category"><img style="width:100%; height:100%;" src="'.$catimg.'" alt="" /></a>
                <div class="home-imgtitle"><span>'.$catname.'</span><span class="home-arwimg"></span></div></div>';      
            if($i==19 || $i==21){echo "</div>";}
            if($i==21){ echo "</div>"; }             
          }
          /*Fifth ends*/
          
           /*Sixth block*/
          if($i > 21 && $i < 25){
              if($i == 22){ echo "<div style='float:left; width:100%;'>"; }
              
              echo '<div class="home-images" style="width:'.$width.'; height:'.$height.'; border:none;'.$margin.'"><a class="homeimg-link" href="'.$caturl.'" title="View the products for this category"><img style="width:100%; height:100%;" src="'.$catimg.'" alt="" /></a>
                <div class="home-imgtitle"><span>'.$catname.'</span><span class="home-arwimg"></span></div></div>';     
              
              if($i == 24){ echo "</div>"; }
          }
          /*Sixth ends*/
          
          
          
          //if($i == 4)break;
          $i++;
     }
     
     
}
?>
