<?php
$cat = Mage::getModel('catalog/category')->load(110);
$subcats = $cat->getChildren();

$k=0;
foreach(explode(',', $subcats) as $subcategory){
    $categorycountry = Mage::getModel('catalog/category')->load($subcategory);
    $cats[$categorycountry->getName()]=$subcategory;
}

$response = array();
$posts = array();
$heightarray = array("308", "277", "308", "308", "268", "308", "308", "310", "260", "248", "148", "148", "148", "148", "276", "276",
    "307", "308", "212", "308");
//ksort($cats);
foreach($cats as $subCatid){
    $_category = Mage::getModel('catalog/category')->load($subCatid);      
    $caturl     = "";     
    $baseurl = $this->getBaseUrl();   
    $margin = "";
    $catimg  = $_category->getImageUrl();
    $catname = $_category->getName();
    $caturls = $_category->getUrl();
    $page_title = $_category->getMetaTitle();
    $height = $heightarray[array_rand($heightarray)];
    
    if($_category->getIsActive()){
        if($_category->getImageUrl()){
            $posts[] = array('image'=> ''.$catimg.'', 'url'=> $caturls, 'width'=> 300, 'height'=> $height, 'price'=> $page_title, "name"=> $catname);
            $k++;
        }
    }
}
$response['result'] = $posts;
$count = count($posts);
$response['total']= $count;
$fp = fopen('waterfall/data/home/homespecials.json', 'w');
fwrite($fp, json_encode($response));
fclose($fp);
?>
<div id="container2" style="width: auto; margin: 0 auto;"></div>
<script type="text/x-handlebars-template" id="waterfall-tpl2">
{{#result}}
    <div class="item">
        <div class="price">
            <span class="price">{{price}}</span>
        </div>
        <a href="{{url}}" style="background-image:url('{{image}}');height='{{height}}';">
            <img src="" width="{{width}}" height="{{height}}" style="visibility:hidden;"/>
        </a>
        <a class="home-imgtitle" href="{{url}}">
            <span>{{name}}</span><span class="home-arwimg"></span>
        </a>
    </div>
{{/result}}
</script>

<script type="text/javascript">
$wf = jQuery.noConflict();
$wf('#container2').waterfall({
itemCls: 'item',
colWidth: 300,  
gutterWidth: 15,
gutterHeight: 15,
checkImagesLoaded: false,
callbacks: {
    renderData: function (data2, dataType) {
        var tpl,
            template,
            resultNum2 = data2.total;               
            if (resultNum2 === <?php echo $count;?>) {
                $wf('#container2').waterfall('pause', function() {
                    //$waterfall('#waterfall-message').html('<div id="header" style="text-align:center;"><h1>no more data</h1></div>');
                    //alert('no more data');
                   });
            }    
            if ( dataType === 'json' ||  dataType === 'jsonp'  ) { // json or jsonp format
                tpl = $wf('#waterfall-tpl2').html();
                template = Handlebars.compile(tpl);
                    return template(data2);
            } else { // html format
                return data2;
            }
        }
    },
path: function(page) {
    return '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>waterfall/data/home/homespecials.json?page='+page;
}
});
</script>
<style>
    #waterfall-loading {
        display: none;
    }
</style>