<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('');?>js/new/examples.css" media="all" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('');?>js/new/transitions.css" media="all" />

    <!--[if lt IE 9]>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <![endif]-->
    <!--[if (gte IE 9) | (!IE)]><!-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <!--<![endif]-->

    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src="<?php echo $this->getSkinUrl('');?>js/new/jquery.collagePlus.js"></script>
    <script src="<?php echo $this->getSkinUrl('');?>js/new/jquery.removeWhitespace.js"></script>
    <script src="<?php echo $this->getSkinUrl('');?>js/new/jquery.collageCaption.js"></script>
  
    <script type="text/javascript">

    // All images need to be loaded for this plugin to work so
    // we end up waiting for the whole window to load in this example
    $as =jQuery.noConflict();
    $as(window).load(function () {
        $as(document).ready(function(){
            collage();
            $as('.Collage').collageCaption();
        });
    });


    // Here we apply the actual CollagePlus plugin
    function collage() {
        $as('.Collage').removeWhitespace().collagePlus(
            {
                'fadeSpeed'     : 2000,
                'targetHeight'  : 200,
                'effect'        : 'effect-4',
                'direction'     : 'vertical'
            }
        );
    };

    // This is just for the case that the browser window is resized
    var resizeTimer = null;
    $as(window).bind('resize', function() {
        // hide all the images until we resize them
        $as('.Collage .Image_Wrapper').css("opacity", 0);
        // set a timer to re-apply the plugin
        if (resizeTimer) clearTimeout(resizeTimer);
        resizeTimer = setTimeout(collage, 200);
    });
    </script>

<?php 
    $_helper = Mage::helper('catalog/category');
    $_categories = $_helper->getStoreCategories();
    if (count($_categories) > 0): ?>
    <div class="Collage effect-parent">
        <?php foreach($_categories as $_category): ?>
        <?php $caturl =$_helper->getCategoryUrl($_category);
         $catid =$_category->getId(); ?>
           <div class="Image_Wrapper">
                <a href="<?php echo $caturl; ?>">
                    <?php 
                    $_category = Mage::getModel('catalog/category')->load($catid);
                    $productCollection = Mage::getResourceModel('catalog/product_collection')
                            ->addCategoryFilter($_category)
                            ->load();        
                    $pid='';
                    foreach($productCollection as $p){
                        $pid[] = $p->getId();
                    }
                    $newpid=array_rand($pid);
                    $product = Mage::getModel('catalog/product')->load($newpid);
                     $imgurl = $product->getImageUrl();
                    ?>
                    <img src="<?php echo $imgurl;?>" />
                    <a class="home-imgtitle" href="<?php echo $caturl;?>" style="position: relative;">
                        <span><?php echo $_category->getName().$product->getName(); ?></span>
                        <span class="home-arwimg"></span>
                    </a>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>