<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?php echo $block->getChildHtml(); ?>
    <?php break; ?>

<?php endswitch; ?>
<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl  = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$customStyle = $mediaUrl.'css/dulcefina/custom-style.css';
?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $customStyle; ?>" />
<link href="https://fonts.googleapis.com/css?family=Cairo:200,300,400,600,700,900" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Oleo+Script:400,700" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps:400,700" rel="stylesheet">   
<link href="<?php echo $mediaUrl; ?>css/dulcefina/font-awesome.min.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" href="<?php echo $block->getUrl(''); ?>pub/media/css/owlcarousel/owl.carousel.min.css">

<!-- For product Qty plus minus sign -->
<script>
require([
         'jquery',
         'jquery/ui',
         ],
         function($, spinner) {
              $(".spintest").spinner({
                   min: 1,
              });
         }
    );
</script>
<!-- For product Qty plus minus sign -->

<!-- respionsive menu close js -->
<script type="text/javascript">
require([
 "jquery"
], function($,click){

jQuery(".custom-close-toggle-menu").click(function(){ 
jQuery('html').removeClass("nav-open");
jQuery('html').removeClass("nav-before-open");
});
});
</script>