<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700|Open+Sans+Condensed:700,300,300italic|Open+Sans:400,300italic,400italic,600,600italic,700,700italic,800,800italic|PT+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'/>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getUrl(''); ?>pub/media/css/googlemap/css/style.css">
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.20&sensor=false"></script>
<script type="text/javascript" src="<?php echo $block->getUrl(''); ?>pub/media/css/googlemap/js/map.js"></script>
<?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-page-google-map')->toHtml();?>
<div class="google-map-outer">
	<div class="google-map">
		<div class="category-inner-list google-map-list">
			<div id="map-canvas"/></div>
		</div>
	</div>
</div>