<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-page-about-us')->toHtml();?>


<div class="map-bg-content">
  <div class="map_content_outer">
    <h3>Dulcefina</h3>
    <ul>
      <li><i class="fa fa-location-arrow" aria-hidden="true"></i> <span class="address">4221 S Tamiami Trl,<br/> Sarasota FL 34231 <span> </li>
      <li><i class="fa fa-mobile" aria-hidden="true"></i><span class="mobile-number"> 941-444-1103 # 501</spa></li>
      <li><i class="fa fa-clock-o" aria-hidden="true"></i> <span class="timing-map">Mon-Fri: 11:00am to 6::00pm <br/>Sat: 11:00am to 5:00pm
      <br/>Sun: 12:00pm to 4:00pm</span></li>
    </ul>
  </div> 
</div>   
