<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    if($category){
	   	//echo $category->getId();
	   	$country_name = $category->getName();
	    //echo $category->getParentId();
	    if($category->getParentId() == 8){
	    	$country_name_lower = strtolower($country_name);
	    	$country_name_image =  $block->getUrl('').'pub/media/css/category-flag/'.$country_name_lower.'.png';
	    	echo "<div class='product_list_page_flag_outer text-center'><img class='product_list_page_flag' src='$country_name_image'></div>";
	    }
    }
?>
<?php /*
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
	$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$categoryHelper = $this->helper('Magento\Catalog\Helper\Category');	
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory'); 
?>
<div class="sidebar_outer">
	<h1>Product Categories</h1>
	<div class="cat_list-outer">
		<ul class="cat_list-outer-ul">
		<?php
				foreach($categoryHelper->getStoreCategories() as $category){
					$category_name = $category->getName();
					$category_url = $categoryHelper->getCategoryUrl($category);
					if($category->getId() != 8 && $category->getId() != 110){ 
						//echo($_productCollection->count());
			?>
					<li class="sub-categories-list"><a href="<?php echo $category_url ; ?>"><span><?php echo $category_name; ?></span></a></li>
			<?php } } ?>
			</ul>
	</div>
	
	
	<div class="price_list-outer" style="display: none">
		<h1>Price</h1>
		<ul class="items price_list-outer-ul">
			<li class="item">
				<a href="?price=20-30">
					<span class="price">$20.00</span> - <span class="price">$29.99</span>
				</a>
			</li>
			<li class="item">
				<a href="?price=30-40">
					<span class="price">$30.00</span> - <span class="price">$39.99</span> 
				</a>
			</li>
			<li class="item">
				<a href="?price=40-50">
					<span class="price">$40.00</span> - <span class="price">$49.99</span>
				</a>
			</li>
			<li class="item">
				<a href="?price=50-60">
					<span class="price">$50.00</span> - <span class="price">$59.99</span>
				</a>
			</li>
			<li class="item">
				<a href="?price=60-">
					<span class="price">$60.00</span> and above 
				</a>
			</li>
		</ul>
	</div>
</div>
*/?>
