<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_Jet
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */
?>
<div class="accordion">
	<div class="entry-edit form-inline">
		<div class="section-config">
			<div class="entry-edit-head">
				<div class="entry-edit-head admin__collapsible-block">
					<span class="entry-edit-head-link" id="ced-support-link"></span> <a
						onclick="Fieldset.toggleCollapse('ced-support','');return false;"
						href="#ced-support-link" id="ced-support-head" class="">Cedcommerce
						Support</a>
				</div>
			</div>
			<fieldset id="ced-support" class="admin__collapsible-block"
					  style="display: none;">
				<ul>
					<a target="_blank"
					   href="http://support.cedcommerce.com/kb/faq.php?cid=9">Jet
						Integration Knowledge base</a>
				</ul>
			</fieldset>
			<script type="text/javascript">
				//&lt;![CDATA[
				require(['prototype'],
					function() {Fieldset.applyCollapse('ced-support');});
				//]]&gt;
			</script>
		</div>
		<div class="section-config">
			<div class="entry-edit-head">
				<div class="entry-edit-head admin__collapsible-block">
					<span class="entry-edit-head-link" id="documentation-link"></span>
					<a onclick="Fieldset.toggleCollapse('documentation','');return false;"
					   href="#documentation-link" id="documentation-head" class="">Documentation</a>
				</div>
			</div>
			<fieldset id="documentation" class="admin__collapsible-block"
					  style="display: none;">
				<ul>
					<a target="_blank"
					   href="http://cedcommerce.com/cedgen/index/download/?file=jet/jet-magento-integration.0.3.1.pdf">Jet
						Integration Extension User Guide</a>
				</ul>
			</fieldset>
			<script type="text/javascript">//&lt;![CDATA[
				require(['prototype'], function() {Fieldset.applyCollapse('documentation');});
				//]]&gt;
			</script>
		</div>
		<div class="section-config">

			<div class="entry-edit-head">
				<div class="entry-edit-head admin__collapsible-block">
					<span class="entry-edit-head-link" id="jet-video-link"></span> <a
						onclick="Fieldset.toggleCollapse('jet-video','');return false;"
						href="#jet-video-link" id="jet-video-head" class="">Integration
						Video from Jet.com</a>
				</div>
			</div>

			<fieldset id="jet-video" class="admin__collapsible-block"
					  style="display: none;">
				<ul>
					<li><a target="_blank" href="https://youtu.be/sFOhhX0iAOw">Integration
							Process Introduction of Jet.com</a></li>
					<li><a target="_blank" href="https://youtu.be/e0jg73m1L_I">API
							Overview</a></li>
					<li><a target="_blank" href="https://youtu.be/aKEF2kBNs6A">Merchant
							Basic Information Setup at Partner Portal</a></li>
					<li><a target="_blank" href="https://youtu.be/MVHCjB7jhww">Products
							API call test</a></li>
					<li><a target="_blank" href="https://youtu.be/4UsuZux4vug">Products
							Overview</a></li>
					<li><a target="_blank" href="https://youtu.be/MVHCjB7jhww">Products
							API call test</a></li>
					<li><a target="_blank" href="https://youtu.be/q1rW7wFzBAg">Orders
							Setup</a></li>
					<li><a target="_blank" href="https://youtu.be/7ZUjRQLTxUw">Returns
							Setup </a></li>
					<li><a target="_blank"
						   href="https://developer.jet.com/v1.0/page/integration-videos">Integration
							Videos </a></li>
				</ul>
			</fieldset>
			<script type="text/javascript">//&lt;![CDATA[
				require(['prototype'], function() {Fieldset.applyCollapse('jet-video');});
				//]]&gt;</script>
		</div>
	</div>
</div>