<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<section class="home-search-wrapper">
<div class="container">
  <div class="row">
<div class="col-sm-5">

    <div style = "display:none" class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
  
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                
               <!--  <label class="label" for="search" data-role="minisearch-label">
                   <span><?php /* @escapeNotVerified */ //echo __('Search'); ?></span>
               </label> -->
                
                <div class="control">
                     
                            <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                  <img src="http://www.dulcefina.com/skin/frontend/default/dulcefina/images/search.png" alt=""><?php /* @escapeNotVerified */ //echo __('Search'); ?>
                </button>
                              <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>

                    
                </div>
            </div>
           
        </form>
</div>
<div class="col-sm-7">
<div class="color-bar-header">
          <ul class="swatches">
                <label>View sweets by colors:</label><li>
                    
                 <?php 
                   for($i=1; $i<=12; $i++)
                   {                 
                   $margin = "";
                   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                   $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                  $baseurl =  $storeManager->getStore()->getBaseUrl();
                   $pageurl = "";
                   switch($i){
                   case 1: $width='40px'; $height='40px'; $margin='margin: 0 4px 0 0;'; $pagename = 'Brown'; $pageurl=$baseurl.'brown.html';
                   break;
                   case 2: $width='40px'; $height='40px'; $margin='margin:0;'; $pagename = 'White'; $pageurl=$baseurl.'white.html';
                   break;
                   case 3: $width='40px'; $height='40px'; $margin='margin:0 0 0 4px;'; $pagename = 'Yellow'; $pageurl=$baseurl.'yellow.html';
                   break;
                   case 4: $width='40px'; $height='40px'; $margin='margin:0;'; $pagename = 'Purple';  $pageurl=$baseurl.'purple.html';
                   break;
                   case 5: $width='40px'; $height='40px'; $pagename = 'Green';  $pageurl=$baseurl.'green.html';
                   break;
                   case 6: $width='40px'; $height='40px'; $margin='margin:0 0 4px;'; $pagename = 'Orange';  $pageurl=$baseurl.'orange.html';
                   break;
                   case 7: $width='40px'; $height='40px'; $margin='margin:0;'; $pagename = 'Blue';  $pageurl=$baseurl.'blue.html';
                   break;
                   case 8: $width='40px'; $height='40px'; $pagename = 'Red';  $pageurl=$baseurl.'red.html';
                   break;
                   case 9: $width='40px'; $height='40px'; $margin='margin-top: 0;';  $pagename = 'Pink';  $pageurl=$baseurl.'pink.html';
                   break;
                   case 10: $width='40px'; $height='40px'; $margin='margin-top: 0;'; $pagename = 'Black';  $pageurl=$baseurl.'black.html';
                   break;
                   case 11: $width='40px'; $height='40px'; $margin='margin-top: 0;';  $pagename = 'Silver';  $pageurl=$baseurl.'silver.html';
                   break;
                   case 12: $width='40px'; $height='40px'; $margin='margin-top: 0;';  $pagename = 'Gold';  $pageurl=$baseurl.'gold.html';
                   break;
                   default : $width='30%';
                   break;
                   }                   

           $mediaUrl =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
                   $imgurl = $mediaUrl .'images/color_bar/'.$i.'.png';
                   echo "<div id='color_br'>";
                    if($i<5){
                    if($i==1){echo " <div style='width:100%;'>";}
                    if($i==2){echo " <div style=''>"; }
                    echo '<a class="homeimg-link" href="'.$pageurl.'" title=""><img style="float:left; margin-top: 0;" src="'.$imgurl.'" alt="" title="'.$pagename.'" /></a>';      
                    if($i==3){echo "</div>"; }
                    if($i==4){echo "</div>"; }        
                    }
                    if($i>4 && $i<9){
                    if($i==5){ echo " <div style='width:100%;'>"; }
                    if($i==6){ echo "<div style=''>";}
                    echo '<a class="homeimg-link" href="'.$pageurl.'" title=""><img style="float:left; margin-top: 0;" src="'.$imgurl.'" alt=""  title="'.$pagename.'"/></a>'; 
                    if($i==7){ echo "</div>";}
                    if($i==8){echo "</div>"; }
                    }
                    if($i>8 && $i<13){
                    if($i==9){ echo " <div style='width:100%;'>"; }
                    if($i==10){ echo "<div style=''>";}
                    echo '<a class="homeimg-link" href="'.$pageurl.'" title=""><img style="float:left; '.$margin.'" src="'.$imgurl.'" alt="" title="'.$pagename.'"/></a>'; 
                    if($i==11){ echo "</div>";}
                    if($i==12){echo "</div>"; }
                    }
                    echo "</div>";
                    }
                   ?>
               </li>
           </ul>
        </div>
</div>


</div>
</div>
</section>
