<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
        <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
      </ul>
</nav>      
        
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="" style="display: block">
        <img src="<?php echo $block->getUrl(''); ?>pub/static/frontend/Magento/luma/en_US/images/logo.png" />      
    </a>
        
<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>     
           
         <li class="level0 nav-20 last level-top ui-menu-item" role="presentation">
        	<a href="<?php echo $block->getUrl(''); ?>Sarasota/" class="level-top ui-corner-all" id="ui-id-22" tabindex="-1" role="menuitem">
        		<span>Sarasota</span>
        	</a>
        </li>
        
         <li class="level0 nav-20 last level-top ui-menu-item" role="presentation">
        	<a href="<?php echo $block->getUrl(''); ?>candy_buffet/" class="level-top ui-corner-all" id="ui-id-22" tabindex="-1" role="menuitem">
        		<span>Buffet</span>
        	</a>
        </li>
        
         <li class="level0 nav-20 last level-top ui-menu-item" role="presentation">
        	<a href="<?php echo $block->getUrl(''); ?>about-us/" class="level-top ui-corner-all" id="ui-id-22" tabindex="-1" role="menuitem">
        		<span>About</span>
        	</a>
        </li>
       
    </ul>
</nav>

<div class="headr-cart" id="header-cart-top" style="display:block;width: 130px; position: absolute; left: 1076.5px;">
<a style="padding-left: 3px;" href="<?php echo $block->getUrl(''); ?>checkout/cart/">
<img src="<?php echo $block->getUrl(''); ?>pub/static/frontend/Magento/luma/en_US/images/cart.png" alt=""></a>
<a style="padding-left: 3px;" href="<?php echo $block->getUrl(''); ?>checkout/cart/">Checkout: </a>
<div style="clear:both;"></div>
<div class="headr-links">
 <div class="user-links">
 <a class="user-links-first" style="padding-left: 10px;" href="<?php echo $block->getUrl(''); ?>customer/account/login/">Login</a>
 <a style="padding-right: 10px;" href="<?php echo $block->getUrl(''); ?>customer/account/create/">Register</a>
</div>
 </div>
</div>